FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache openssl

COPY package.json package-lock.json* ./
COPY prisma/ ./prisma/
RUN npm install
RUN npx prisma@5.22.0 generate

CMD ["npx", "prisma@5.22.0", "migrate", "deploy"]
